version: '3.8'
services:
  replic-app:
    container_name: replic-app
    build: .
    volumes:
      - /replic-app/venv
      - /replic-app/__pycache__
      - /Users/alex...:/replic-app # Absolute path to docker image directory
      - /Users/alex.../pre-shared-key.txt:/replic-app/pre-shared-key.txt # Absolute path to pre-shared-key.txt
    environment:
      FLASK_ENV: development
    ports:
      - 8443:8443